server.port: 8080

spring:
  datasource:
    username: root
    password: 376-376
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Moscow
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false



# example values
indexing-settings:
  sites:
#    - url: https://dombulgakova.ru/
#      name: dombulgakova.ru
#    - url: https://radiomv.ru/
#      name: radiomv.ru
    - url: https://Skillbox.ru
      name: Skillbox.Ru
  userAgent: "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2049.0 Safari/537.36"
  referrer:  https://google.com
  currentTimeZone: Europe/Moscow

 # Output to a logfile named application.log.
logging.file.name: application.log


